[colors.bright]
black = "#262320"
blue = "#75a0ad"
cyan = "#7e9fa7"
green = "#577881"
magenta = "#b2ada6"
red = "#e29073"
white = "#f8ebde"
yellow = "#e4a673"

[colors.cursor]
cursor = "#d9d9d9"
text = "#ffffff"

[colors.normal]
black = "#191816"
blue = "#5b7b85"
cyan = "#668087"
green = "#425a61"
magenta = "#8b8782"
red = "#c27b62"
white = "#e2d7cc"
yellow = "#c28d62"

[colors.primary]
background = "#191816"
foreground = "#e2d7cc"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.9
